### ISSUE TITLE
Admin interface

### ISSUE THREAD

**Issue by DuccioGuazzelli** [sonatra/sonatra-security-bundle#11]
Hi guys,

i'm working on a symfony3 + sonata admin and user bundle.

Security bundle is now installed, i've created the admin form for roles, permissions, sharings but it seems that not all the fields of the entity are shown.

Example: parents and children for Role.

Can you provide some help?

Thanks in advance

D

**Comment by francoispluchino** [comment]
I don't use the bundles of Sonata Project, So I cannot help you for the UI and forms, but I can help you about this bundle.

Are your entities correctly mapped in Doctrine?

**Comment by DuccioGuazzelli** [comment]
I think that this is the main question:

we use orm with annotation, so i took the xml code from you installation procedure, i converted it to annotation and then generated the entity as described here
http://symfony.com/doc/current/doctrine/reverse_engineering.html

So the resulting Role Entity for example is defined:

<?php

namespace VilleBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Sonatra\Component\Security\Model\Role as BaseRole;

/**
 * Role
 *
 * @ORM\Table(name="core_role")
 * @ORM\Entity
 */
class Role extends BaseRole
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="core_role_id_seq", allocationSize=1, initialValue=1)
     */
    protected $id;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="VilleBundle\Entity\Role", mappedBy="children")
     */
    protected $parents;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="VilleBundle\Entity\Role", inversedBy="parents")
     * @ORM\JoinTable(name="core_role_children",
     *   joinColumns={
     *     @ORM\JoinColumn(name="role_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="children_role_id", referencedColumnName="id")
     *   }
     * )
     */
    protected $children;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->parents = new \Doctrine\Common\Collections\ArrayCollection();
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
        $this->permissions = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function __toString()
    {
        return "Ruoli";
    }      

}

**Comment by francoispluchino** [comment]
This is not specified in the doc, but add a `on-delete="CASCADE"` on each `join-column` of `children` association metadata. Your mapping looks fine. Can you detail your problem? Because I did not understand if you have a problem with this bundle or other bundles.

**Comment by DuccioGuazzelli** [comment]
Hi, again.

The problem seems to be in the Sonata admin auto generate form procedure.

I edited my form mapper this way:

`

    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('name')
            ->add('parents')
            ->add('children')
        ;
    }

`

and now i'm able to create role with parents and children.

Now i'm trying to setup Permission form and i got from auto procedure the following fields:
- operation
- contexts
- class
- field
- roles
- sharing entries

Roles and sharing entries are correctly working, operation, class and field are simple input text field and contexts seems not working

My formmapper is:


`
    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('operation')
            ->add('contexts')
            ->add('class')
            ->add('field')
            ->add('roles')
            ->add('sharingEntries')
        ;
    }


`
Do i have to add some more params to the field definitions?

Thanks again

**Comment by francoispluchino** [comment]
Define only the form fields:
- operation (required, the name of permission, ex: `view`, `create`, `update`, `delete`, `undelete`, `read`, `edit`, `manage-permissions`, etc...)
- class (optional, the FQCN)
- field (optional, the property name in class)
- roles (optional, the role names, ex: `ROLE_ADMIN`)

The `contexts` field is an advanced use, and probably not necessary for you. Do not add the `sharingEntries` relationship in the form.

However, I do not know if the bundle you use for the roles can work with their helpers, or if you must imperatively build a "standard" form, I explain:

The permissions are not defined for each role, but they are defined globally, and afterwards, you can associate the permissions with each role. You must therefore build a dedicated form to:

- les "global" permissions (without class, without field), ex. `manage-permissions`
- les "class" permissions (with class, with field), ex. `view`, `create`, `update`, `delete`, `undelete`
- les "field" permissions (with class, with field), ex. `read`, `edit`

Small detail, it isn't required to define the permissions for the fields of a class, You can look the [configuration](https://github.com/sonatra/sonatra-security-bundle/blob/master/DependencyInjection/Configuration.php) for sections `default_permissions`, `permissions` and `permissions.fields`, it's very flexible to limit the manual configuration.

**Example:**

If you use the object filter service (clean the value in object with null value or empty collection), the permissions `read` and `edit` are used instead of `view` and `update`. You can define a mapping permission to map automatically the permission `read` for the field, with the `view` permission on class, and the permission `edit` for the field, with the `update` permission on class. So, when you check the permission `read` on the field of class, the checker will check the permission `view` on the class.

You can also define permissions directly in the configuration, which can be useful for "system" fields, like `id`, `createdAt`, `updatedAt`, etc...

**Config example:**

```yaml
sonatra_security:
    default_permissions:
        fields:
            id:        [read]
            createdAt: [read]
            updatedAt: [read]
        master_mapping_permissions:
            view:      read
            update:    edit
            create:    edit
            delete:    edit
    permissions:
        AppBundle\Entity\User:
            operations:   [view, create, update, delete]
            fields:
                username: [read, edit]
                email:    [read, edit]
                roles:    [read]
        AppBundle\Entity\Post:
            fields:
                title:        ~
                body:         ~
                commentCount: [read]
        AppBundle\Entity\Comment:
            master:                    post
            operations:                [view, create, update, delete]
            fields:
                email:                 [read, edit]
                message:               [read, edit]
```

For this example, the fields `title` and `body` of `Post` class, are ungranted by default for all roles, and the field `commentCount` are only readable for all roles. So, all permissions defined in configuration are availables and granted for all roles.

The `master_mapping_permissions` and `master` work like the fields of a class, but it allows to check the autormizations of an entity associated instead of the field of the class. So, when you check the autorization `edit` for the `email` field of `Comment` class, the checker checks the autorization `update` of the `Post` class.

Of course, for all roles defined by the hierarchy of all roles of current user.

Personally, I create a data loader (doctrine data fixtures) for all permissions, launched with a command, and I create 3 forms to associate each role with the permissions according to the 3 cases of use (global, class, field).

To give you an idea, to build the form of fields permissions, I retrieve all fields (defined in my custom metadata manager), I retrieve all permissions for each fields, and I build a form child for each field to edit each permission.

I hope I have been clear enough about forms and the configuration. :)
