### ISSUE TITLE
How to add permissions programmatically

### ISSUE THREAD

**Issue by bohrsty** [sonatra/sonatra-security-bundle#12]
Hello Francois,
I am quiete new to symfony, but I chose to migrate one of my projects to symfony and while using detailed permission on single pages or page entries in this project, I came to your security bundle... I installed and configured it according to the docs, but I couldn't find information how to use the security and permissions in my code...

I created user, group, role, etc. entities for the security bundle and some other for my business logic (i.e navigation objects). Now I need to add permissions to single navigation entries (objects), that some could be seen by "any" user (anonymous) and others could only be seen by logged in user or groups or roles.

* How would I add these permissions to single object from a controller or from a service?
* Is it possible to set a default permission denying every access (even reading) to any entity (existing ones and every I create in future) until explicitly granted? And how would that be configured?

Thank you for your answers and your work on the bundle.

**Comment by francoispluchino** [comment]
Hi @bohrsty, welcome to the Symfony community!

I don't know if you are familiar with the [Symfony Security](http://symfony.com/doc/current/security.html) and the [Securing services doc](http://symfony.com/doc/current/security/securing_services.html), but this bundle is an "advanced" bundle, so this isn't going to be easy at first if you are not accustomed (but it's done well ;)).

Firstly, I would advise you to read the Symfony security documentations, and after, read the issue #11 (mainly [this comment](https://github.com/sonatra/sonatra-security-bundle/issues/11#issuecomment-305226181)), you will find the operating principle of the permissions.

**Regarding the using of the security checker**

This bundle work with the Symfony Authorization Checker, using the prefix `perm_` before the permission name.

Example:

```php
use Sonatra\Component\Security\Permission\FieldVote;

$this->get('security.authorization_checker')->isGranted('perm_update', $entity);
$this->get('security.authorization_checker')->isGranted('perm_update', PostInterface::class);
$this->get('security.authorization_checker')->isGranted('perm_edit', new FieldVote($entity, 'title'));
$this->get('security.authorization_checker')->isGranted('perm_edit', new FieldVote(PostInterface::class, 'title'));
```
You can use the `@Security` annotation in your controllers:

```php
use Sonatra\Bundle\SecurityBundle\Configuration\Security;

MyController {
    /**
     * @Security("is_granted('perm_view', 'AppBundle\\Entity\\Post')")
     */
    public function getPostsAction()
    {
        //...
    }

    /**
     * @Security("is_granted('perm_view', post)
     */
    public function getPostAction(PostInterface $post)
    {
        //...
    }
}
```

**Regarding the code to manipulate the permissions**

To manipulate the permissions, you can use directly the object instance of permission like any doctrine entity, that is you can use the symfony form, validator, and doctrine to persist or remove the permissions.

The issue #11 will allow you to understand the logic and order to create and associate the permissions with the roles.

**Comment by bohrsty** [comment]
Hi @francoispluchino,
thank you for your support...

Yes I read the mentioned symfony docs, but every examle uses the config files, that isn't very usefull for security on objects, I think.

Checking the permissions isn't the problem, as far as I understood, I can use `@Security` annotations, method calls like `$this->get('security.authorization_checker')->is_granted('perm_...', $entity);` or the integration of the security bundle in doctrine to get only the permitted entity objects.

The difficulty for me is, that I don't use any forms, templates etc., my project uses all the symfony stuff as JSON-api endpoint, so the UI only sends some JSON data to the controller, the controller and some services check the data and inserts maybe new entities and returns some JSON data as response.

So first thing I have to do is, create some permissions and persist them in doctrine:

```php
$rPerm = new Permission();
$rPerm->setOperation('read')
      ->setClass(nulll)
      ->setField(null);

$wPerm = new Permission();
$wPerm->setOperation('write')
      ->setClass(nulll)
      ->setField(null);

$gPerm = new Permission();
$gPerm->setOperation('grant')
      ->setClass(nulll)
      ->setField(null);

$em->persist($rPerm);
$em->persist($wPerm);
$em->persist($gPerm);
$em->flush();
```

Second thing is, in my controller I have to create some entities, that should get some permissions:

```php
class MyController extends Controller {
    public function saveEntityAction(Request $request) {
        
        // get current user
        $user = $this->getUser();
        
        // check the data in $request
        $data = ...
        
        // persist new entity
        $entity = new Entity();
        $entity-> setData($data);

        $em->persist($entity);
        
        // get security entities
        $allUsers = $groupRepository->findOneByName('allUsers');
        $adminRole = $roleRepository->findOneByName('ROLE_ADMIN');

        // set permissions
        // ...STUCK HERE...
        
        $em->flush();
    }
}
```

And now I am stuck (and the mentioned comment in #11 didn't helped), is there a method like:

```php
$this->get('security.authorization_checker')->set_permission([User|Group|Role], ['perm_read'|Permission], $entity);
```
i.e to set different permissions to different security entities:

```php
$this->get('security.authorization_checker')->set_permission($user, $rPerm, $entity);
$this->get('security.authorization_checker')->set_permission($allUsers, $wPerm, $entity);
$this->get('security.authorization_checker')->set_permission($adminRole, $gPerm, $entity);
```

**Comment by francoispluchino** [comment]
It's not necessary to have a specific manager to manage the permissions, use directly the model of the roles:

```php
$permissionView = $permissionRepository->findOneBy(array('operation' => 'view', 'class' => PostInterface::class, 'field' => null));
$adminRole = $roleRepository->findOneByName('ROLE_ADMIN');

$adminRole->addPermission($permissionView);

$em->persist($adminRole);
$em->flush();
```

You can also use directlty the doctrine collection of permissions in roles if you wish it.

```php
$adminRole->getRoles()->add($permissionView);
```

PS. The `security.authorization_checker` service is only to check the permissions, not to manipulate the permissions.

You cannot set permissions directly on entity, but you can use the SharingManager (`sonatra_security.sharing_manager`). You can share an entity with a user, a role, a group, [or an organization]. And you can define roles for this sharing (user only) and/or permissions (but also an activation date and an expiration date for this sharing). Each sharing retrieves automatically the equivalent of the `view` permission of the class. Of course, the user must have permissions on the class (and fields) to retrieve the shared entity, via the permssions of all its roles, or the roles attached to the sharing or directly the permissions attached to the sharing.

The sharing model works with the Subject Identities for the entities (see `Sonatra\Component\Security\Identity\SubjectIdentity`) and Security Identity for the user, role, group, and organization (see `Sonatra\Component\Security\Identity\UserSecurityIdentity`, `Sonatra\Component\Security\Identity\RoleSecurityIdentity`, `Sonatra\Component\Security\Identity\GroupSecurityIdentity` and `Sonatra\Component\Security\Identity\OrganizationSecurityIdentity`).

Like the permissions, use directly the sharing instance, doctrine persist and repository to manage your shares.

You have helpers to get the identities:

- `SubjectIdentity::fromObject($object)`
- `SubjectIdentity::fromClassname($className)`
- `UserSecurityIdentity::fromAccount($user)`
- `UserSecurityIdentity::fromToken($token)`
- `RoleSecurityIdentity::fromAccount($role)`
- `RoleSecurityIdentity::fromToken($token)`
- `GroupSecurityIdentity::fromAccount($group)`
- `GroupSecurityIdentity::fromToken($token)`
- `OrganizationSecurityIdentity::fromAccount($organization)`
- `OrganizationSecurityIdentity::fromToken($organization, $context = null, $roleHierarchy = null)`

All helpers return the instance of `Sonatra\Component\Security\Identity\SecurityIdentityInterface`, and you retrieve the type and the identifier that will must be used for the sharing instance.

Sharing entity required:

- subject class (the classname of entity)
- subject id (the id of entity)
- identity class (the classname of user, role, group or organization)
- identity name (the username, role name, group name or organization name)
- the list of permissions (optional)
- the list of roles (optional)

This library does not include a manager to manage permissions with roles, or sharing with entities, because it uses natively Doctrine, and leaves you the choice to using Doctrine directly, to creating you a specific manager or to using a resource management library (like [sonatra/resource-bundle](https://github.com/sonatra/sonatra-resource-bundle)).

**Comment by bohrsty** [comment]
Hi @francoispluchino,
thank you so far, I think I understood now the design principles of your bundle and I'll now try to find a way using it in my coding...
I close that issue for now, if there arise detail questions or new ones, I'll open a new one...

**Comment by bohrsty** [comment]
Hi @francoispluchino,
I have to reopen this issue, because I cannot find my error. I tried to "deny all permissions" for my Navi entity, but as a result I get the list of all entities that my `findBy(...)` method would retrieve from database if I wouldn't use permission config, but without any field filled (i.e. id is null, strings and array collections are empty)...

I tried to deny permission for all with this configuration:
```yaml
# sonatra security configuration
sonatra_security:
    role_class: AppBundle\Entity\Role
    permission_class: AppBundle\Entity\Permission
    sharing_class: AppBundle\Entity\Sharing
    object_filter:
        enabled: true # Enable the object filter (optional)
    role_hierarchy:
        enabled: true # Enable the role hierarchy for organizational context (optional)
        cache: null # Defined the service cache for role hierarchy (optional)
    security_voter:
        role_security_identity: true # Override the Symfony Role Hierarchy Voter (optional)
        groupable: true # Enable to check the group in the Symfony Security Authorization Checker
    sharing:
        enabled: true
        identity_types:
            AppBundle\Entity\User:
                roleable: true # (optional)
            AppBundle\Entity\Role:
                permissible: true # (optional)
    default_permissions:
        master_mapping_permissions:
            view:      read
            update:    edit
            create:    edit
            delete:    edit
    permissions:
        AppBundle\Entity\Navi:
            enabled: true
    doctrine:
        orm:
            object_filter_voter: true # Ebable the Doctrine ORM Collection Object Filter (optional)
            listeners:
                permission_checker: true # Enable the Doctrine ORM Permission Checker Listener (optional)
                object_filter: true # Enable the Doctrine ORM Object Filter Listener(optional)
                role_hierarchy: true # Enable the Doctrine ORM listener of role hierarchy (optional)
            filters:
                sharing: true # Enable the Doctrine ORM SQL Filter for sharing the entities (optional)
```

(where in
```yaml
    permissions:
        AppBundle\Entity\Navi:
```
I also tried `operations: []` or `master: ~`, all with the same result)

and would have expected to get an empty result from this `findBy()` call:
```php
$repositoryNavi = $this->em->getRepository('AppBundle:Navi');
$naviEntries = $repositoryNavi->findBy(
	array(
		'parent' => null,
		'valid' => true,
		'show' => true
	),
	array('position' => 'ASC')
);
```

Have I misunderstood something, or what would the correct way to deny all permissions for any user/group/role (afterwards I want to use sharing to grant permissions to individual users/groups/roles)?
